---
- name: crowdsec | Create crowdsec directories
  become: true
  ansible.builtin.file:
    path: "{{ docker_data_path }}/core/crowdsec/{{ item }}"
    state: directory
    mode: '0755'
    owner: 1000
    group: "{{ docker_group }}"
  with_items:
    - config
  tags:
    - crowdsec

- name: "crowdsec | Add docker-compose.yml crowdsec"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ item }}"
    group: "{{ docker_group }}"
    mode: '0640'
  with_items:
    - "{{ docker_data_path }}/dc_core_crowdsec.yml"
  vars:
    project_name: core
    containers:
      - crowdsec
    container_volumes:
      - crowdsec_data
      - crowdsec_staging
  tags:
    - crowdsec

- name: "crowdsec | Start crowdsec container" # noqa: no-changed-when
  ansible.builtin.command:
    cmd: >-
      docker compose -f {{ docker_data_path }}/dc_core_crowdsec.yml up -d
    chdir: "{{ docker_data_path }}"
  tags:
    - crowdsec

- name: crowdsec | Enroll crowdsec engine
  community.docker.docker_container_exec:
    container: core-crowdsec-1
    command: "cscli console enroll --name {{ inventory_hostname }}
      {{ crowdsec_enroll_token }}"
  register: crowdsec_enroll
  changed_when:
    - '"successfully enrolled" in crowdsec_enroll.stderr'
  failed_when:
    - '"FATA" in crowdsec_enroll.stderr'
    - '"ERR" in crowdsec_enroll.stderr'
  tags:
    - crowdsec

- name: crowdsec | Ensure traefik bouncer is enrolled
  when: crowdsec_traefik_api_key is undefined
  block:
    - name: crowdsec | Create Traefik bouncer key
      community.docker.docker_container_exec:
        container: core-crowdsec-1
        command: "cscli bouncers add bouncer-traefik -o raw"
      register: crowdsec_traefik_bouncer
      tags:
        - crowdsec

    - name: "crowdsec | Set fact for crowdsec_traefik_api_key"
      ansible.builtin.set_fact:
        crowdsec_traefik_api_key: "{{ crowdsec_traefik_bouncer.stdout }}"
        cacheable: true
      tags:
        - crowdsec

- name: "crowdsec | Add docker-compose.yml crowdsec"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ item }}"
    group: "{{ docker_group }}"
    mode: '0640'
  with_items:
    - "{{ docker_data_path }}/dc_core_crowdsec.yml"
  vars:
    project_name: core
    containers:
      - crowdsec
    container_volumes:
      - crowdsec_data
      - crowdsec_staging
  tags:
    - crowdsec
