---
- name: "semaphore | Add docker-compose.yml semaphore"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ item }}"
    group: "{{ docker_group }}"
    mode: '0640'
  with_items:
    - "{{ docker_data_path }}/dc_management_semaphore.yml"
  vars:
    project_name: management
    containers:
      - semaphore
      - mariadb
    container_volumes:
      - "{{ mariadb_container_name }}"
      - "semaphore"
    mariadb_user: semaphore
    mariadb_container_name: semaphore-mariadb
    mariadb_dbname: semaphoredb
    mariadb_user_password: "{{ semaphore_mariadb_user_password }}"
    mariadb_root_password: "{{ semaphore_mariadb_root_password }}"
    mariadb_mem_limit: 400m
    mariadb_data_path: "{{ mariadb_container_name }}"
  tags:
    - semaphore

- name: "semaphore | Start semaphore container" # noqa: no-changed-when
  ansible.builtin.command:
    cmd: >-
      docker compose -f {{ docker_data_path }}/dc_management_semaphore.yml up -d
    chdir: "{{ docker_data_path }}"
  tags:
    - semaphore

- name: "semaphore | Add Prometheus scraper semaphore"
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK (semaphore)"
    path: "{{ docker_data_path }}/monitoring/prometheus/etc/prometheus.yml"
    block: |2
        - job_name: semaphore_db
          static_configs:
            - targets:
                - semaphore-mariadb-exporter:9104
  when: prometheus_enabled | default(false)
  notify: Restart prometheus container
  tags:
    - semaphore
