---
- name: Hardening installation
  hosts: all
  vars_files:
    - "vars/4_default.yml"
    - "vars/3_versions.yml"
    - "vars/2_site.yml"
    - "vars/1_host/{{ inventory_hostname }}.yml"
    - "vars/custom.yml"
  roles:
    - hardening
