---
- name: Install mailcow
  hosts: mailserver
  become: true
  vars_files:
    - "vars/4_default.yml"
    - "vars/3_versions.yml"
    - "vars/2_site.yml"
    - "vars/1_host/{{ ansible_fqdn }}.yml"
    - "vars/custom.yml"
  roles:
    - mailcow.mailcow
    - mailcow
