---
- name: "Include tasks to deploy traefik container"
  ansible.builtin.include_tasks: containers/traefik.yml
  when: >-
    docker is defined
    and docker.containers is contains('traefik')
  tags:
    - always

- name: "Include tasks to deploy adminer container"
  ansible.builtin.include_tasks: containers/adminer.yml
  when: >-
    docker is defined
    and docker.containers is contains('adminer')
  tags:
    - always

- name: "Include tasks to deploy crowdsec container"
  ansible.builtin.include_tasks: containers/crowdsec.yml
  when: >-
    docker is defined
    and docker.containers is contains('crowdsec')
  tags:
    - always

- name: "Include tasks to deploy nextcloud container"
  ansible.builtin.include_tasks: containers/nextcloud.yml
  when: >-
    docker is defined
    and docker.containers is contains('nextcloud')
  tags:
    - always

- name: "Include tasks to deploy portainer container"
  ansible.builtin.include_tasks: containers/portainer.yml
  when: >-
    docker is defined
    and docker.containers is contains('portainer')
  tags:
    - always

- name: "Include tasks to deploy powerdns container"
  ansible.builtin.include_tasks: containers/powerdns.yml
  when: >-
    docker is defined
    and docker.containers is contains('powerdns')
  tags:
    - always

- name: "Include tasks to deploy powerdns admin container"
  ansible.builtin.include_tasks: containers/powerdns_admin.yml
  when: >-
    docker is defined
    and docker.containers is contains('powerdns-admin')
  tags:
    - always

- name: "Include tasks to deploy semaphore container"
  ansible.builtin.include_tasks: containers/semaphore.yml
  when: >-
    docker is defined
    and docker.containers is contains('semaphore')
  tags:
    - always

- name: "Cleanup docker images"
  community.docker.docker_prune:
    images: true
  tags:
    - always
