---
- name: "1_initial_setup | 1.1.1 Disable unused filesystems"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/modprobe.d/1_1_1_unused_fs.conf"
    line: "install {{ item }} /bin/true"
    owner: root
    group: root
    mode: '0644'
    create: true
  with_items:
    - cramfs
    - squashfs
    - udf
  tags:
    - hardening

- name: "1_initial_setup | 1.1.10 Disable USB Storage"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/modprobe.d/1_1_10_usb_storage.conf"
    line: "install usb-storage /bin/true"
    owner: root
    group: root
    mode: '0644'
    create: true
  tags:
    - hardening

- name: "1_initial_setup | 1.3.1 Ensure AIDE is installed"
  ansible.builtin.package:
    name:
      - aide # 1.3.1
      - aide-common # 1.3.1
  become: true
  register: aide_installed
  tags:
    - always
  notify:
    - "Initialize AIDE"

- name: >-
    1_initial_setup | 1.4.2 Ensure permissions on bootloader config are
    configured
  become: true
  ansible.builtin.file:
    path: "/boot/grub/grub.cfg"
    owner: root
    group: root
    mode: "0400"
  tags:
    - hardening

- name: >-
    1_initial_setup | 1.5.1 Ensure address space layout randomization (ASLR)
    is enabled
  become: true
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
  tags:
    - hardening

- name: >-
    1_initial_setup | 1.5.3 Ensure Automatic Error Reporting is not enabled
  become: true
  ansible.builtin.package:
    name:
      - apport
    state: absent
  tags:
    - always

- name: "1_initial_setup | 1.5.4 Ensure core dumps are restricted (sysctl)"
  become: true
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: '0'
    state: present
  tags:
    - hardening

- name: "1_initial_setup | 1.5.4 Ensure core dumps are restricted (limits)"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/security/limits.d/1_5_4_disable_dimps.conf
    line: "* hard core 0"
    owner: root
    group: root
    mode: "0400"
    create: true
  tags:
    - hardening

- name: >-
    1_initial_setup | 1.7.2 & 1.7.3 Ensure login warning banner is configured
    properly
  become: true
  ansible.builtin.copy:
    src: "files/etc/issue"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - issue
    - issue.net
  tags:
    - hardening
