---
- name: "3_firewall | 3.2.1 Ensure packet redirect sending is disabled"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  tags:
    - hardening

- name: "3_firewall | 3.2.2 Ensure IP forwarding is disabled"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding
  tags:
    - hardening

- name: "3_firewall | 3.3.1 Ensure source routed packets are not accepted"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
    - net.ipv6.conf.all.accept_source_route
    - net.ipv6.conf.default.accept_source_route
  tags:
    - hardening

- name: "3_firewall | 3.3.2 Ensure ICMP redirects are not accepted"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects
  tags:
    - hardening

- name: "3_firewall | 3.3.3 Ensure secure ICMP redirects are not accepted"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.conf.default.secure_redirects
    - net.ipv4.conf.all.secure_redirects
  tags:
    - hardening

- name: "3_firewall | 3.3.4 Ensure suspicious packets are logged"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
  tags:
    - hardening

- name: "3_firewall | 3.3.5 Ensure broadcast ICMP requests are ignored"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.icmp_echo_ignore_broadcasts
  tags:
    - hardening

- name: "3_firewall | 3.3.6 Ensure bogus ICMP responses are ignored"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.icmp_ignore_bogus_error_responses
  tags:
    - hardening

- name: "3_firewall | 3.3.7 Ensure Reverse Path Filtering is enabled"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
  tags:
    - hardening

- name: "3_firewall | 3.3.8 Ensure TCP SYN Cookies is enabled"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv4.tcp_syncookies
  tags:
    - hardening

- name: "3_firewall | 3.3.9 Ensure IPv6 router advertisements are not accepted"
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/30_firewall.conf
  with_items:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
  tags:
    - hardening

- name: "3_firewall | 3.4 Uncommon Network Protocols"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/modprobe.d/3_4_uncommon_protocols.conf"
    line: "install {{ item }} /bin/true"
    owner: root
    group: root
    mode: '0644'
    create: true
  with_items:
    - dccp
    - sctp
    - rds
    - tipc
  tags:
    - hardening

- name: "3_firewall | 3.5.2 Configure nftables"
  become: true
  ansible.builtin.package:
    name:
      - ufw # 2.3.4
    state: absent
  tags:
    - hardening
