---
- name: "4_logging_auditing | 4.1.1.2 Ensure auditd service is enabled"
  ansible.builtin.systemd:
    name: auditd
    state: started
    enabled: true
  become: true

- name: "4_logging_auditing | 4.1.3 Configure auditd rules"
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/audit/rules.d/{{ item | basename }}"
    owner: root
    group: root
    mode: '0640'
  with_fileglob:
    - files/etc/auditd/rules.d/*.rules
  notify:
    - Restart auditd
  tags:
    - hardening

- name: >-
    4_logging_auditing | 4.2.1.3 & 4.2.1.4 Ensure journald is configured to
    compress large log files
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/systemd/journald.conf"
    line: "{{ item }}"
  with_items:
    - Compress=yes
    - Storage=persistent
  notify:
    - Restart journald
  tags:
    - hardening
