---
- name: 5_access_auth | 5.1.2 Ensure permissions on /etc/crontab are configured
  become: true
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: file
    owner: root
    group: root
    mode: "0600"
  with_items:
    - crontab
  tags:
    - hardening

- name: >-
    5_access_auth | 5.1.3 - 5.1.7 Ensure permissions on /etc/cron.* are
    configured
  become: true
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  with_items:
    - cron.d
    - cron.daily
    - cron.hourly
    - cron.monthly
    - cron.weekly
  tags:
    - hardening

- name: "5_access_auth | 5.2 Configure SSH Server "
  become: true
  ansible.builtin.template:
    src: "templates/etc/ssh/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: "0600"
  notify:
    - Restart sshd
  tags:
    - hardening

- name: "5_access_auth | 5.3 Configure privilege escalation"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ item }}"
    owner: root
    group: root
    mode: '0600'
    create: true
  with_items:
    - Defaults logfile="/var/log/sudo.log" # 5.3.3
    - Defaults timestamp_timeout=15 # 5.3.6
  tags:
    - hardening

- name: >-
    5_access_auth | 5.4.1 Ensure password creation requirements are configured
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/security/pwquality.conf"
    line: "{{ item }}"
  with_items:
    - minlen = 14
    - minclass = 4
    - dcredit = -1
    - ucredit = -1
    - lcredit = -1
    - ocredit = -1
  tags:
    - hardening

- name: >-
    5_access_auth | 5.4.4 Ensure password hashing algorithm is up to date with
    the latest standards
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/login.defs"
    line: ENCRYPT_METHOD yescrypt
    regexp: "^ENCRYPT_METHOD"
  tags:
    - hardening

- name: >-
    5_access_auth | 5.5.1.4 Ensure inactive password lock is 30 days or less
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/default/useradd"
    line: INACTIVE=30
    regexp: "^INACTIVE"
  tags:
    - hardening

- name: >-
    5_access_auth | 5.5.4 Ensure default user umask is 027 or more restrictive
    (login.defs)
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/login.defs"
    line: UMASK 027
    regexp: "^UMASK"
  tags:
    - hardening

- name: >-
    5_access_auth | 5.5.4 Ensure default user umask is 027 or more restrictive
    (/etc/profile)
  become: true
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: umask 027
    regexp: "^umask"
  with_items:
    - /etc/profile
    - /etc/bash.bashrc
  tags:
    - hardening

- name: >-
    5_access_auth | 5.5.5 Ensure default user shell timeout is 900 seconds or
    less
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/profile.d/tmout.sh"
    line: readonly TMOUT=900 ; export TMOUT
    regexp: "^readonly TMOUT="
    owner: root
    group: root
    mode: '0644'
    create: true
  tags:
    - hardening
