---
- name: "ubuntu_hardening | Install packages required for hardening"
  ansible.builtin.package:
    name:
      - apparmor # 1.6.1.1
      - systemd-timesyncd # 2.1.3.2
      - auditd # 4.1.1.1
      - audispd-plugins # 4.1.1.1
      - systemd-journal-remote # 4.2.1.1.1
      - libpam-pwquality # 5.4.1
  become: true
  tags:
    - always

- name: "ubuntu_hardening | Chapter 1: Initial Setup"
  ansible.builtin.include_tasks: ubuntu/1_initial_setup.yml

- name: "ubuntu_hardening | Chapter 2: Services"
  ansible.builtin.include_tasks: ubuntu/2_services.yml

- name: "ubuntu_hardening | Chapter 3: Firewall"
  ansible.builtin.include_tasks: ubuntu/3_firewall.yml

- name: "ubuntu_hardening | Chapter 4: Logging and Auditing"
  ansible.builtin.include_tasks: ubuntu/4_logging_auditing.yml

- name: "ubuntu_hardening | Chapter 5: Access, Authentication and Authorization"
  ansible.builtin.include_tasks: ubuntu/5_access_auth.yml
